import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import { Architecture, FileAnalysis, Finding, Mark } from '../types';

/**
 * Reads/writes the .audit/ directory. All data is human-readable and git-friendly:
 *   audit.json / files/<hash>.json / marks.json / findings/<id>.json / architecture.md / report.md
 */
export class AuditStore {
  readonly root: string;

  constructor(workspaceRoot: string) {
    this.root = path.join(workspaceRoot, '.audit');
  }

  private ensureDir(dir: string): void {
    fs.mkdirSync(dir, { recursive: true });
  }

  private writeJson(file: string, data: unknown): void {
    this.ensureDir(path.dirname(file));
    fs.writeFileSync(file, JSON.stringify(data, null, 2) + '\n', 'utf8');
  }

  private readJson<T>(file: string): T | undefined {
    try {
      return JSON.parse(fs.readFileSync(file, 'utf8')) as T;
    } catch {
      return undefined;
    }
  }

  init(): void {
    this.ensureDir(this.root);
    const meta = path.join(this.root, 'audit.json');
    if (!fs.existsSync(meta)) {
      this.writeJson(meta, {
        version: 1,
        createdAt: new Date().toISOString(),
        tool: 'audit-assistant',
      });
    }
  }

  // ---------- File analysis ----------

  /** File name uses the sha1 of the relative path (avoids separator/length issues); the raw path is kept inside for humans */
  private analysisPath(relPath: string): string {
    const key = crypto.createHash('sha1').update(relPath.replace(/\\/g, '/')).digest('hex');
    return path.join(this.root, 'files', `${key}.json`);
  }

  saveFileAnalysis(analysis: FileAnalysis): void {
    this.init();
    this.writeJson(this.analysisPath(analysis.path), analysis);
  }

  /** Load a file analysis; still returned when currentHash mismatches (staleness is handled by the caller) */
  loadFileAnalysis(relPath: string): FileAnalysis | undefined {
    return this.readJson<FileAnalysis>(this.analysisPath(relPath.replace(/\\/g, '/')));
  }

  // ---------- Project structure ----------

  /** Writes both architecture.json (for programmatic reuse) and architecture.md (human-readable / git-shared) */
  saveArchitecture(arch: Architecture): void {
    this.init();
    this.writeJson(path.join(this.root, 'architecture.json'), arch);
    fs.writeFileSync(path.join(this.root, 'architecture.md'), architectureMarkdown(arch), 'utf8');
  }

  loadArchitecture(): Architecture | undefined {
    return this.readJson<Architecture>(path.join(this.root, 'architecture.json'));
  }

  // ---------- source/sink marks ----------

  loadMarks(): Mark[] {
    return this.readJson<Mark[]>(path.join(this.root, 'marks.json')) ?? [];
  }

  saveMarks(marks: Mark[]): void {
    this.init();
    this.writeJson(path.join(this.root, 'marks.json'), marks);
  }

  upsertMark(mark: Mark): void {
    const marks = this.loadMarks();
    const i = marks.findIndex((m) => m.id === mark.id);
    if (i >= 0) {
      marks[i] = mark;
    } else {
      marks.push(mark);
    }
    this.saveMarks(marks);
  }

  deleteMark(id: string): void {
    this.saveMarks(this.loadMarks().filter((m) => m.id !== id));
  }

  // ---------- Call-chain findings ----------

  loadFindings(): Finding[] {
    const dir = path.join(this.root, 'findings');
    let names: string[];
    try {
      names = fs.readdirSync(dir).filter((n) => n.endsWith('.json'));
    } catch {
      return [];
    }
    const findings: Finding[] = [];
    for (const n of names) {
      const f = this.readJson<Finding>(path.join(dir, n));
      if (f) {
        findings.push(f);
      }
    }
    return findings;
  }

  saveFinding(finding: Finding): void {
    this.init();
    this.writeJson(path.join(this.root, 'findings', `${finding.id}.json`), finding);
  }

  deleteFinding(id: string): void {
    try {
      fs.unlinkSync(path.join(this.root, 'findings', `${id}.json`));
    } catch {
      // Ignore if it no longer exists
    }
  }
}

function architectureMarkdown(arch: Architecture): string {
  const lines: string[] = [
    '# Project Structure',
    '',
    `> Generated by Audit Assistant at ${arch.generatedAt}${arch.model ? ` (model ${arch.model})` : ''}`,
    '',
  ];
  if (arch.overview) {
    lines.push(arch.overview, '');
  }
  lines.push('## Structure Tree', '', '```text', arch.tree, '```', '', '## Module Responsibilities', '');
  for (const m of arch.modules) {
    lines.push(
      `- **${m.name}** (${m.fileCount} files, ${m.loc.toLocaleString('en-US')} LOC)${m.description ? `: ${m.description}` : ''}`,
    );
    for (const f of m.sampleFiles.slice(0, 3)) {
      lines.push(`  - ${f}`);
    }
  }
  if (arch.edges.length) {
    lines.push('', '## Module Dependencies', '');
    for (const e of arch.edges.slice(0, 40)) {
      lines.push(`- ${e.from} → ${e.to}${e.weight > 1 ? ` (${e.weight} references)` : ''}`);
    }
  }
  lines.push('');
  return lines.join('\n');
}
